[env]
MISE_FETCH_REMOTE_VERSIONS_TIMEOUT = "30s"

_.python.venv = {
  path = ".venv",
  create = true,
}

[tools]
python = "3.11"

[tasks.test]
run = 'make install test'

[tasks.lint]
run = 'make install lint'
